### ISSUE TITLE
Code in 0-starter doesn't match write up

### ISSUE THREAD

**Issue by djohnston30** [MicrosoftDocs/mslearn-react#2]
Trying to follow https://docs.microsoft.com/en-us/learn/modules/react-get-started/ -- it notes that the starter project (0-starter) should have two folders (public, src) and have snowpack.config.js included - but it has none of that.  All that's there is the package.json. Without that, following the tute and running npm start script results in a snowpack server with no index file - pretty confusing for a user just starting up.  

Best,
D

**Comment by technbuzz** [comment]
Yeah it's missing. I just wend to the `code/1-getting-started/end` folder and copied the `snowpack.config.js` file. It works after that

**Comment by djohnston30** [comment]
Did the same - should be fine for anyone with a basic familiarity with
node, ms learn, etc... more thinking for front end folks who are just
starting with concepts around running builds, etc

**Comment by paoramati** [comment]
This tripped me up too. The language here should be changed to e.g. 'in ```/code/3-state-events/end```'

![image](https://user-images.githubusercontent.com/22553916/114697860-ee1dd400-9d0d-11eb-9685-3b38420f9b8c.png)

**Comment by d4shm1r** [comment]
I did everything manually. I created two empty files both public and src. And it work with snowpack.config.js file.

**Comment by GeekTrainer** [comment]
This is completely my fault. I filed PR #1 and forgot to actually merge it. Sorry for all of the confusion!!
